version: '3.7'

services:
  hub:
    image: selenium/hub:3.141.59
    container_name: hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - chrome
      - hub
    command: pytest tests/ --alluredir allure-results
    environment:
      - BROWSER=chrome

  allure:
    image: frankescobar/allure-docker-service
    restart: unless-stopped
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      KEEP_HISTORY: "TRUE"
      CHECK_RESULTS_EVERY_SECONDS: 1
    ports:
      - "4040:4040"
      - "5050:5050"
    depends_on:
      - app

networks:
  app:
    driver: bridge
